### ISSUE TITLE
'Sampling for model' error

### ISSUE THREAD

**Issue by TRueger87** [ctross/SkewCalc#1]
Hi! Recently read your paper and am keen to try out this new index. I keep getting the same error when running your example code:

*****
> M_index_stan(RS,Time) 

SAMPLING FOR MODEL 'b5f34275290d5ca6c2cc73eb1096ec16' NOW (CHAIN 1).
Chain 1: empty_nested() must be true before calling recover_memory()
[1] "Error in sampler$call_sampler(args_list[[i]]) : "             
[2] "  empty_nested() must be true before calling recover_memory()"
error occurred during calling the sampler; sampling not done
Stan model 'b5f34275290d5ca6c2cc73eb1096ec16' does not contain samples.
*****
> M_index_stan(d$rs[which(d$group=="AFROCOLOMBIAN" & d$sex=="M")],d$age[which(d$group=="AFROCOLOMBIAN" & d$sex=="M")]) 

SAMPLING FOR MODEL 'b5f34275290d5ca6c2cc73eb1096ec16' NOW (CHAIN 1).
Chain 1: empty_nested() must be true before calling recover_memory()
[1] "Error in sampler$call_sampler(args_list[[i]]) : "             
[2] "  empty_nested() must be true before calling recover_memory()"
error occurred during calling the sampler; sampling not done
Stan model 'b5f34275290d5ca6c2cc73eb1096ec16' does not contain samples.
****

Is it something I did? Any ideas?

Thanks!
Theresa

**Comment by ctross** [comment]
This error isn't coming from my package, but from Stan. 

Do you have a working C++ compiler and Stan build installed?

I know that the latest R update requires that a new version of RTools be installed. Updating R, RTools, and Stan should fix the issue.

https://github.com/stan-dev/projpred/issues/9

**Comment by TRueger87** [comment]
Thank you, I got it to run now. I followed your advice and updated the compiler and Stan. Also, I had to make sure that the rstan package wasn't called before calling SkewCalc, otherwise I ran into trouble. Might be specific to my system though. Looking forward to working with this package!
