### ISSUE TITLE
Doesn't load the packages in R

### ISSUE THREAD

**Issue by robayosalek** [ctross/SkewCalc#2]
Hi, I´m working with marmot skew and I was looking for a r code to process the data. I try to run this code but it didn't work. I don't know if you could help me
![image](https://user-images.githubusercontent.com/94763374/142740461-156ff851-8bf2-4fee-80e8-d006bed066e0.png)

**Comment by ctross** [comment]
Try running

install.packages("coda")

And then run what you did before.

**Comment by robayosalek** [comment]
Thank you very much!

![image](https://user-images.githubusercontent.com/94763374/142742108-db26d8b6-24ac-448e-9716-3d8b92e2f869.png)
